### ISSUE TITLE
Image url gives error

### ISSUE THREAD

**Issue by prathamApp** [fangpenlin/avataaars-geneator#14]
Hello, 
On hitting the image url that I get of the avataar, on another tab gives me this error.
![sketch10](https://user-images.githubusercontent.com/30404370/44643056-b773dd80-a9ec-11e8-8e84-5df16046052e.png)

Please help.

**Comment by cb109** [comment]
Can confirm, the image serving app seems to be down at the moment. Pinging @fangpenlin so she is aware :)

**Comment by fangpenlin** [comment]
@prathamApp @cb109 can you provide the URL? also the API is actually provided by @gkoberger, I guess maybe he can help on this issue?

**Comment by cb109** [comment]
Example URL that **was** broken yesterday: https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShaggyMullet&accessoriesType=Prescription02&hairColor=Brown&facialHairType=Blank&clotheType=Hoodie&clotheColor=Black&eyeType=Squint&eyebrowType=Default&mouthType=Grimace&skinColor=Light

It seems to be fixed already :) I guess this can be closed, cheers!

**Comment by fangpenlin** [comment]
👍

**Comment by gkoberger** [comment]
Whoops, I didn't notice this Issue, but I did notice it was down and fixed it :)
